use crate::utils;

pub fn run() {
    let keys = [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "comma",
        "semicolon",
        "period",
        "degree",
        "periodcentered",
        "less",
        "equal",
        "greater",
        "minus",
        "asciitilde",
        "dead_circumflex",
        "percent",
        "parenleft",
        "parenright",
        "bracketleft",
        "bracketright",
        "plus",
        "asterisk",
        "numbersign",
        "apostrophe",
        "bar",
        "slash",
        "question",
        "ssharp",
        "udiaeresis",
        "Udiaeresis",
        "odiaeresis",
        "Odiaeresis",
    ];
    let replacements = [
        "◾",
        "◽︎",
        "❑",
        "❖",
        "‣",
        "➤",
        "⮚",
        "✗",
        "✘",
        "✔",
        "◁",
        "□",
        "●",
        "◌",
        "◉",
        "☙",
        "❦",
        "❧",
        "⸺",
        "⁓",
        "ˆ",
        "℔",
        "﴾",
        "﴿",
        "⁅",
        "⁆",
        "⌘",
        "⁂",
        "※",
        "♪",
        "✝",
        "℅",
        "�",
        "\u{2007}",
        "\u{2009}",
        "\u{2003}",
        "\u{200B}",
        "◌\u{200D}", // ZWJ, so looks bad in output
    ];

    for (key, replacement) in keys.iter().zip(replacements.iter()) {
        print!("<dead_stroke> <{}>:", key);
        utils::print_rule(replacement);
    }
}
